---
title: "Number of CPGs"
format:
  html:
    toc: true
    toc-depth: 5
    html-math-method: katex
    embed-resources: true
    smooth-scroll: true
editor: visual
execute:
  echo: true
  include: true
---

# Set up

```{r set-up}
library(IlluminaHumanMethylation450kanno.ilmn12.hg19)
library(rio)
library(tidyverse)
library(ggVennDiagram)
library(gridExtra)
library(RColorBrewer)
library(janitor)
library(GenomicRanges)
```

# Gene Lists

```{r}
kegg_immune <- import("~/Documents/GitHub/hs_power_analysis/gene_lists/human_KEGG_immune_pathways_unique_gene_list.csv")
dim(kegg_immune) #1236    6

kegg_cvd <- import("~/Documents/GitHub/hs_power_analysis/gene_lists/KEGG_CVD_unique_gene_symbols.csv")
dim(kegg_cvd) # 607   1

# kegg_cvd2 <- import("~/Documents/GitHub/hs_power_analysis/gene_lists/KEGG_CVD_unique_genes.csv")
# identical(kegg_cvd$gene_symbol, kegg_cvd2$gene_symbol)

kegg_endocrine <- import("~/Documents/GitHub/hs_power_analysis/gene_lists/KEGG_endocrine_metabolic_unique_gene_symbols.csv")

# kegg_endocrine2 <- import("~/Documents/GitHub/hs_power_analysis/gene_lists/KEGG_endocrine_metabolic_unique_genes.csv")
# identical(kegg_endocrine$gene_symbol, kegg_endocrine2$gene_symbol)

all_kegg_ids <- c(kegg_immune$gene_symbol, kegg_cvd$gene_symbol, kegg_endocrine$gene_symbol)
length(all_kegg_ids) #2309

unique_kegg_ids <- unique(all_kegg_ids)
length(unique_kegg_ids) #1729

unique_kegg_ids <- unique(kegg_cvd$gene_symbol)
length(unique_kegg_ids) #607

# ath_df <- import("~/Documents/GitHub/hs_power_analysis/gene_lists/hsa05417_Lipid_and_atherosclerosis_genes.csv")
# unique_kegg_ids <- unique(ath_df$gene_symbol)
# length(unique_kegg_ids) #216

# unique_kegg_ids <- c("ABCG1", "CAMK2B", "NFKB1", "ABCA1", "LDLR")
```

# Illumina EPIC 450k

```{r}
anno_450k <- getAnnotation(IlluminaHumanMethylation450kanno.ilmn12.hg19)
anno_450k_df <- as.data.frame(anno_450k)

anno_450k_subset <- anno_450k_df %>%
  select(chr, pos, Name, UCSC_RefGene_Name)
dim(anno_450k_subset) #485512      4

anno_450k_subset_long <- anno_450k_subset %>%
    separate_rows(UCSC_RefGene_Name, sep = ";") %>%
    distinct()
dim(anno_450k_subset_long) # 526,742      4
```

# Common Genes

Of the 1729 genes, we have 1525 in the 450k array

```{r}
anno_genes <- anno_450k_subset_long %>%
  filter(!is.na(UCSC_RefGene_Name), UCSC_RefGene_Name != "") %>%
  pull(UCSC_RefGene_Name) %>%
  unique()

kegg_genes <- unique_kegg_ids %>%
  na.omit() %>%
  unique()

venn_list <- list(
  `450k` = anno_genes,
  `kegg` = kegg_genes
)

ggVennDiagram(venn_list)
```

# Probes List

32550 distinct probes 12378

```{r}
anno_450k_subset_long_filt <- anno_450k_subset_long %>%
  filter(UCSC_RefGene_Name %in% unique_kegg_ids)  

dim(anno_450k_subset_long_filt) #12661

unique(anno_450k_subset_long_filt$chr) # we have chrY and chrX too...

anno_450k_subset_long_filt_xy <- anno_450k_subset_long_filt%>%
  filter(!chr %in% c("chrY", "chrX"))

unique(anno_450k_subset_long_filt_xy$chr) # we have chrY and chrX too...
dim(anno_450k_subset_long_filt_xy) #12416     4

n_distinct(anno_450k_subset_long_filt_xy$Name) #12378 distinct probes
n_distinct(anno_450k_subset_long_filt_xy$UCSC_RefGene_Name) #537 distinct genes

hs_data_Ms <- import("~/Documents/GitHub/healthy_start/data/Borengasser_170160-110104/CB_m_norm_batch_plate.csv")

length(intersect(names(hs_data_Ms), anno_450k_subset_long_filt_xy$Name)) #11299

```
